### PR TITLE
Add support to configure and use proxy

### PR DESCRIPTION
**Pull request by magynhard**
This PR implements https://github.com/miyataka/fcmpush/issues/38

Looking forward to add this feature and releasing a new version of the gem.

### CODE REVIEW

**Comment by magynhard** [comment]
@miyataka
Can you give any feedback or news to this PR?

**Comment by miyataka** [comment]
Thank you for your contribution.

Haven't done review yet.
Checking whether HTTPS_PROXY (not HTTP_PROXY) is possible with option of `net-http-persistent`.

BTW, you need HTTP_PROXY feature only?? @magynhard

**Comment by magynhard** [comment]
Yes, my PR is based (only) on the options of `net-http-persistent`.

See its concrete proxy documentation here
* by option https://www.rubydoc.info/gems/net-http-persistent/3.0.0/Net%2FHTTP%2FPersistent:proxy=
* by env environment https://www.rubydoc.info/gems/net-http-persistent/3.0.0/Net/HTTP/Persistent#proxy_from_env-instance_method

As far as i understand and expect, when setting explicitly the `#proxy=` option, it will apply to all requests, when using the ENV feature, it only considers the HTTP_PROXY env variable. Did not test, but i guess even then it will be considered by all requests, even https ones.

I'm fine with only using this both `net-http-persistant` options without adding any addiontal feature.

**Comment by miyataka** [comment]
@magynhard I've merged this Pull-Request for run tests. (and maybe a few refactor)
Please wait for a while until the new version is released.

**Comment by magynhard** [comment]
@miyataka thank you for your information!

Looking forward for your new version release with this feature. :+1:

**Pull request merged**
